name: truthscan_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^0.13.0

  # State management
  provider: ^6.1.4

  # File picker
  file_picker: ^10.1.2

  # PDF viewer
  syncfusion_flutter_pdfviewer: ^20.4.54

  # Responsive UI
  responsive_framework: ^1.5.1

  # PDF text extraction
  pdf_text: ^0.5.0

  # Persistent storage
  shared_preferences: ^2.5.3

  # Bottom navigation bars
  salomon_bottom_bar: ^3.3.2
  stylish_bottom_bar: ^1.1.1

  # App icon configuration
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/launchericon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/images/launchericon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/images/launchericon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/images/launchericon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
